/**
 * Regenerates `src/defaults/*.ts` from the JSON in `config/`.
 *
 * The compiled binary cannot read the repository, so the defaults it ships with
 * are baked in as TypeScript modules. Keeping two copies invites drift, so this
 * script is the only sanctioned way to update them and runs as part of `build`.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { desktopThemeSchema, mappingConfigSchema } from "../src/schema"

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")

async function readJson(relativePath: string): Promise<unknown> {
  return JSON.parse(await readFile(resolve(ROOT, relativePath), "utf8"))
}

async function main(): Promise<void> {
  const themeRaw = await readJson("config/theme.json")
  const mappingRaw = await readJson("config/mapping.json")

  // Validate before baking: a broken default would ship inside the binary.
  const theme = desktopThemeSchema.parse(themeRaw)
  mappingConfigSchema.parse(mappingRaw)

  await mkdir(resolve(ROOT, "src/defaults"), { recursive: true })

  await writeFile(
    resolve(ROOT, "src/defaults/theme.ts"),
    [
      `// GENERATED by scripts/sync-defaults.ts from config/theme.json — do not edit.`,
      ``,
      `import type { z } from "zod"`,
      `import type { desktopThemeSchema } from "../schema"`,
      ``,
      `/** Written to the user's config directory on first run. */`,
      `export const DEFAULT_THEME: z.infer<typeof desktopThemeSchema> = ${JSON.stringify(theme, null, 2)}`,
      ``,
    ].join("\n"),
    "utf8",
  )

  await writeFile(
    resolve(ROOT, "src/defaults/mapping.ts"),
    [
      `// GENERATED by scripts/sync-defaults.ts from config/mapping.json — do not edit.`,
      ``,
      `import type { z } from "zod"`,
      `import type { mappingConfigSchema } from "../schema"`,
      ``,
      `/**`,
      ` * How Orb's primitive families are structured. Not a user preference, so`,
      ` * this stays compiled in rather than being written to disk.`,
      ` */`,
      `export const DEFAULT_MAPPING: z.input<typeof mappingConfigSchema> = ${JSON.stringify(mappingRaw, null, 2)}`,
      ``,
    ].join("\n"),
    "utf8",
  )

  console.log("synced src/defaults/{theme,mapping}.ts from config/")
}

main().catch((error: unknown) => {
  process.stderr.write(`sync-defaults failed: ${error instanceof Error ? error.message : String(error)}\n`)
  process.exitCode = 1
})
